cxx_library(
  name = 'uvpp',
  # header_namespace = 'uvpp',
  header_namespace = '',
  exported_headers = subdir_glob([
    ('include', '*.hh')
  ]),
  srcs = glob([
    'src/*.cc'
  ]),
  visibility = [
    '//...',
  ],
  deps = [
    '//deps/libuv:libuv'
  ],
)

cxx_binary(
  name = 'uvpp-demo',
  # header_namespace = 'uvpp',
  header_namespace = '',
  srcs = [ 'main.cc' ],
  deps = [
    ':uvpp',
  ],
)
