cxx_library(
  name = 'libriver',
  header_namespace = 'river',
  exported_headers = subdir_glob([
    ('include', '**/*.hh'),
  ]),
  srcs = glob([
    'src/**/*.cc',
  ]),
  visibility = [
    '//...',
  ],
  deps = [
    '//uvv8:uvv8',
  ],
  compiler_flags = [
    '-std=c++1z',
  ],
)

cxx_binary(
  name = 'river',
  header_namespace = 'river',
  srcs = glob([
    'main.cc',
  ]),
  deps = [
    ':libriver',
  ],
)
